# Config relating to the Lazygit UI
gui:

  # Config relating to colors and styles.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  theme:

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - cyan

# AI generated commit message using AICommit2 ref : https://github.com/jesseduffield/lazygit/issues/3212#issuecomment-2402357613
customCommands:
  - key: <c-g>
    description: GenerateAI commit using conventional commits
    command: aicommit2
    context: files
    subprocess: true
    showOutput: true
